function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 11-Oct-2023 11:46:02

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    100 0 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1.9 -1.7 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [1.9 -1.7 0;
    10.1 -1.8 0;
    17 -1.9 0;
    24.4 -1.9 0;
    31 -1.6 0;
    37.3 -0.6 0;
    40.8 0.9 0;
    46.1 1.8 0;
    51.5 2 0;
    55.4 0.9 0;
    58.3 -0.7 0;
    63.5 -1.8 0;
    71.3 -1.9 0;
    78.6 -1.9 0;
    86.3 -1.9 0;
    95 -1.8 0];
speed = [15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [46.2 -1.5 0], ...
    'RearOverhang', 1, ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.truckMesh, ...
    'Name', 'Car1');

