function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 11-Oct-2023 11:07:57

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [5 0 0;
    100 0 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [8 -1.8 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [8 -1.8 0;
    16.2 -1.8 0;
    24.2 -1.7 0;
    33.3 -1.7 0;
    42 -0.8 0;
    46 1 0;
    49.8 2 0;
    54.9 2 0;
    59 1.3 0;
    63.8 -1.3 0;
    72.2 -2 0;
    80.2 -1.5 0;
    89.9 -1.7 0;
    97.9 -1.7 0];
speed = [15;15;15;15;15;15;15;15;15;15;15;15;15;15];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [51.8 -2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');

